version: "2.4"
services:
  ros2:
    image: ros2
    container_name: ros2-docker
    runtime: nvidia
    environment:
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    network_mode: bridge
