version: "2.4"
services:
  ros2:
    build:
      context: "./"
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    container_name: ros2-docker
    runtime: nvidia
    environment:
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "../:/ros2"
    network_mode: bridge
